#pragma once
#include <cstdint>
#include <string>
#include <cstddef>
#include <optional>
#include <expected>
#include <memory>
#include <algorithm>
#include <vector>
#include <Buffer.h>
#include <format>
#include "UdpEndpoint.h"