#pragma once
#include <cstdint>
#include <string>
#include <cstddef>
#include <optional>
#include <expected>
#include <memory>
#include <algorithm>
#include <vector>
#include <Buffer.h>
#include <format>
#include <mutex>
#include "UdpEndpoint.h"
#include <unordered_map>
#include <cstring>
#include <atomic>
#include <span>
#include <array>